# Project information
site_name: DeepDeck
site_url: https://deepdeck.co
site_author: DeepSea Developments
site_description: >-
  DeepDeck is an OpenSource MacroPad (mini mechanical keyboard) that enables 
  you to get more productive by using it with your work/hobby/leisure programs.

# Copyright
copyright: Copyright &copy; 2022 - 2024 DeepDeck by DeepSea Developments

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: material/github
  # Default values, taken from mkdocs_theme.yml
  language: en
  favicon: assets/favicon.ico
  logo: assets/logo.svg
  features:
    # - navigation.instant #Without this, the jump from home page to other subpages fails.
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.instant.progress
    
    - toc.follow
    
    - search.suggest
    - search.highlight
    - search.share

    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link


  palette: 
    # Palette toggle for light mode
    - scheme: deepdeck
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode


repo_url: https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw
repo_name: DeepDeck.Ahuyama.fw
edit_uri: edit/mkdocs/docs/

extra_css:
  - stylesheets/extra.css

hooks:
  - overrides/hooks/shortcodes.py

extra:
  analytics:
    provider: google
    property: G-1WMF7F09F0
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.


markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde



plugins:
 
  - search
  - tags
  - glightbox
  - blog:
      archive: false
      archive_toc: true
      categories: true
      categories_toc: true
      blog_toc: true
      post_url_format: "{slug}"
      post_excerpt: required
      post_excerpt_separator: <!-- more -->
      pagination_per_page: 5
      pagination_keep_content: true
  - render_swagger

    # CI=1 mkdocs build
  - group:
      enabled: !ENV CI
      plugins:
        - social
        # - git-revision-date-localized:
        #     enable_creation_date: true
        #     type: timeago
        # - git-committers:
        #     repository: DeepSea-Developments/DeepDeck.Ahuyama.fw
        #     branch: mkdocs
        - minify:
            minify_html: true

  # INSIDERS=1 mkdocs build
  - group:
      enabled: !ENV INSIDERS 
      plugins:
        - meta


  # Page tree
nav:
  - Home: index.md
  - Quick Start Guide: 
    - First steps: en/QuickStartGuide/qsg.md
    - Firmware update: en/QuickStartGuide/qsg-firmware-update.md
    - Wifi Setup: en/QuickStartGuide/wifi-setup.md
    - Layer creation: en/QuickStartGuide/layer-setup.md
    - Add a battery: en/QuickStartGuide/battery.md
    - Support: en/Resources/support.md
    - Thank you!: en/QuickStartGuide/thankyou.md
    - Hardware specs: en/QuickStartGuide/hw-specs.md
    - Firmware specs: en/QuickStartGuide/fw-specs.md
    - FAQ and Troubleshooting: en/QuickStartGuide/faq.md
  - Open Source:
    - Open Source: en/opensource/opensource.md
    - Conventions: en/opensource/conventions.md
    - Firmware: 
      - en/opensource/fw/firmware.md
      - How to setup VS code: en/opensource/fw/vscode-setup.md
      - Understanding repo structure: en/opensource/fw/repository.md
      - How to contribute?: en/opensource/fw/fw_contribute.md
    - Installing software:
      - DeepDeck installer: en/opensource/installer/installer.md
    - API:
      - ESP32 API: en/opensource/api/api.md
  - Download: 
    - en/Resources/index.md
    - 3d printed accesories: en/Resources/3d-prints.md
    - Other accesories: en/Resources/accessories.md
  - Blog: 
    - blog/index.md