site_name: DeepDeck
theme:
  name: material
  custom_dir: docs
  icon:
    repo: material/github
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

repo_url: https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw
repo_name: DeepDeck
edit_uri: edit/master/docs/

extra_css:
  - stylesheets/extra.css


markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde






  # Page tree
nav:
  - Home: index.md
  - Getting started:
    - Installation: vscode-setup.md
    - Configuration: 
      - deepdeck-configuration.md
      - Layer: layer-configuration.md
      - Macro: macro-configuration.md
      - Knob: knob-configuration.md
  - Known issues: known-issues.md
