authors:
  ElectroNick:
    name: Nick Velasquez
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/5274871
  JDavid:
    name: Juan Vargas
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/112643890